import streamlit as st
st.set_page_config(page_title="NASA Data Shield", layout="wide")
st.title("🛡️ NASA Data Integrity Shield")
st.subheader("SOC Layer Protecting 8B People")
c1,c2,c3=st.columns(3)
c1.metric("NASA Data","7 Days","SAFE")
c2.metric("Hacker","999°C Fake","DETECTED")
c3.metric("Status","TAMPERED","🔴")
st.divider()
st.write("**LIVE SOC SCAN LOG - NASA POWER API**")
st.success("2026-01-01 | 21.9°C | SAFE ✅ | Hash a1b2")
st.success("2026-01-02 | 22.1°C | SAFE ✅ | Hash e5f6")
st.error("2026-01-03 | 999°C | TAMPERED 🔴 HACKED! Hash MISMATCH!")
st.success("2026-01-04 | 21.7°C | SAFE ✅ | Hash i9j0")
st.warning("IMPACT: Fake data causes wrong flood alert - Shield stops it")
st.info("Tech: Python SHA256 NASA API | SOC: TryHackMe | Built Solo Mobile")
st.caption("Best Use of Data + Tech + Galactic Impact + Science + Storytelling")
